name: Monthly release

on:
  schedule:
    - cron: "30 23 19 * *"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_and_check.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7

      - name: Get date
        id: date
        run: echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Publish release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.date.outputs.date }}
          target_commitish: ${{ github.sha }}
          files: "sougou.dict,sougou.dict.yaml,sougou_dict.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
